#include "Boards.h"

namespace Boards {

const char* const winBoard[MAX_Y] = {
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
	 "W==============================================================================W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                   ||    You Completed all the stages    ||                   W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                Your Score:                                   W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                        Press ESC to go back to the menu                      W",
	 "W                                                                              W",
	 "W==============================================================================W",
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
};

const char* const scoreBoard[MAX_Y] = {
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
	 "W==============================================================================W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                            ||  SCORE BOARD  ||                               W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                        Press ESC to go back to the menu                      W",
	 "W                                                                              W",
	 "W==============================================================================W",
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
};

const char* const screenErrorBoard[MAX_Y] = {
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
	 "W==============================================================================W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                               Press ESC to exit                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W==============================================================================W",
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
};

const char* const loseBoard[MAX_Y] = {
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
	 "W==============================================================================W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                          ||     GAME   OVER     ||                           W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                  Your Score:                                 W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                        Press ESC to go back to the menu                      W",
	 "W                                                                              W",
	 "W==============================================================================W",
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
};

const char* const riddleBoard[MAX_Y] = {
	 "????????????????????????????????????????????????????????????????????????????????",
	 "?==============================================================================?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                Answer:                                       ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?                                                                              ?",
	 "?==============================================================================?",
	 "????????????????????????????????????????????????????????????????????????????????"
};

const char* const manuBoard[MAX_Y] = {
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
	 "W==============================================================================W",
	 "W                                                                              W",
	 "W                              ***   Manu   ***                                W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                         Press 1 - Start a new game                           W",
	 "W                                                                              W",
	 "W                          Press 2 - Colors (ON/OFF)                           W",
	 "W                                                                              W",
	 "W                           Press 3 - Score Board                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                   Press 8 - Present instructions and keys                    W",
	 "W                                                                              W",
	 "W                              Press 9 - EXIT                                  W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W==============================================================================W",
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
};

const char* const guideBoard[MAX_Y] = {
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
	 "W                                                                              W",
	 "W                           ~~~ INSTRUCTIONS ~~~                               W",
	 "W                                                                              W",
	 "W                     PRESS ESC TO EXIT THE INSTRUCTIONS                       W",
	 "W                         How to Play Adventure World:                         W",
	 "W                                                                              W",
	 "W    - The objective is to navigate your characters to the last room,          W",
	 "W      by solving riddles and use different tools.                             W",
	 "W    - Use the keys below to control your character.                           W",
	 "W                                                                              W",
	 "W                                CONTROLS:                                     W",
	 "W            A - Move Left                     J - Move Left                   W",
	 "W            D - Move Right                    L - Move Right                  W",
	 "W            W - Move Up                       I - Move Up                     W",
	 "W            X - Move Down                     M - Move Down                   W",
	 "W            S - Stay in Place                 K - Stay in Place               W",
	 "W            E - Pick/Dispose Element          O - Pick/Dispose Element        W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                          Good luck and have fun!                             W",
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
};

const char* const gamePaused[MAX_Y] = {
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                          ||    GAME PAUSED    ||                             W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                              PRESS ESC TO REMUSE                             W",
	 "W                           PRESS H TO GO BACK TO MENU                         W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "W                                                                              W",
	 "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
};

}
